### ISSUE TITLE
`Hide()` hashes output even if input implements Concealer interface

### ISSUE THREAD

**Issue by ashmrtn** [alcionai/clues#29]
Not really sure which way forward we want to take this, but there's a bit of oddness around how `marshal` and `clues.Hide` interact. `marshal` will conceal the output if the item being concealed implements the `Concealer` interface. This data is then stored in what I assume is meant to be the "string" representation of the item. `Hide` then [calls](https://github.com/alcionai/clues/blob/e24d7940e07a1aba601518f4766f4d0f584aba84/secrets.go#L122) `Conceal` on the (potentially already concealed) representation generated by `marshal`. This can cause nicely formatted but obfuscated information to lose useful data as it's reduced to a single hash

Open question: what is `secret.str` field meant to represent?

**Comment by ryanfkeepers** [comment]
> Open question: what is secret.str field meant to represent?

`secret.s` is the plain text representation of `secret.v`, which is the original value.  This is opposed to `secret.h`, which is the hashed text version of `secret.v`.  No, I also don't know why I wanted to go with single letter property names at the time.  I'll make a fix for that sometime.

> a bit of oddness around how marshal and clues.Hide interact. marshal will conceal the output if the item being concealed implements the Concealer interface.

Question for clarification: is the issue when calling `json.Marshal(clues.Hide(foo))`, or is the issue from marshalling any concealer interface.  And does the struct in question return a hashed string when `String()` is called, or a plain text string?

**Comment by ashmrtn** [comment]
thanks for the clarification! To round out the discussion (though some of this was out of band) the precise situation I'm hitting is calling `clues.Hide(<thing that implements Concealer>)`. When doing this I find that the final output is a hash of the output generated by the thing that implements `Concealer` instead of just the output from `<thing>.Conceal()` which is what I'd kind of expect

This could be me calling things incorrectly in which case I can go update the code I have

**Comment by ryanfkeepers** [comment]
> When doing this I find that the final output is a hash of the output generated by the thing that implements Concealer instead of just the output from <thing>.Conceal() which is what I'd kind of expect

Yup!  The current implementation was allowing a double-marshalling.  Passing a concealer c into Hide() called `marshal(c)`, which would ask c to conceal itself.  Clues would then conceal _that_ output again.  Now if someone passes in a concealer, it will return that concealer's hash and plaintext directly, instead of re-hashing anything.

Marking this as closed with the merger of https://github.com/alcionai/clues/pull/30
